#
# Copyright (c) 2019 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
CONFIG_NCS_SAMPLES_DEFAULTS=y
CONFIG_ESB=y
CONFIG_DK_LIBRARY=y
CONFIG_CLOCK_CONTROL=y
CONFIG_ESB_FAST_SWITCHING=y
CONFIG_ESB_FAST_CHANNEL_SWITCHING=y
CONFIG_ESB_RX_FIFO_SIZE=40
CONFIG_ESB_TX_FIFO_SIZE=2

CONFIG_ESB_PTX_TX_LENGTH=12


# 1kHz packet rate
# CONFIG_ESB_PTX_DELAY=1000
# 2kHz packet rate
# CONFIG_ESB_PTX_DELAY=500
# 4kHz packet rate
# CONFIG_ESB_PTX_DELAY=150
CONFIG_ESB_PTX_DELAY=125
CONFIG_SPIN_VALIDATE=n
CONFIG_PM=n
CONFIG_SOC_NRF_FORCE_CONSTLAT=y
CONFIG_TIMESLICING=n
